### ISSUE TITLE
Инкременты итератора

### ISSUE THREAD

**Issue by avasyukov** [turfe/Container#3]
Реализации работают и проходят те тесты, что есть, но всё-таки не до конца целостны:
https://github.com/turfe/Container/blob/6b50d81de27acf394b31e90ba909e3d417b82353/List_Iterator.h#L32-L43

А именно:
- пост-инкремент может упасть при попытке инкрементить что-то не то
- пост-инкремент таки должен возвращать *прошлое* состояние, которое *до* инкремента - см. теорию по теме

**Comment by turfe** [comment]
Исправил
